services:
  # message Broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: audio-broker
    ports:
      - "5672:5672"   # rabbitmq port
      - "15672:15672" # management ui
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # node api 
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: audio-api
    ports:
      - "3000:3000"
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    volumes:
      - audio_data:/app/uploads
    depends_on:
      - rabbitmq

  # rust worker (dsp engine)
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: audio-worker
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    volumes:
      - audio_data:/app/data
    depends_on:
      - rabbitmq

volumes:
  audio_data: